### ISSUE TITLE
Error running eliot-tree on Python 3

### ISSUE THREAD

**Issue by zloidemon** [jonathanj/eliottree#35]
Versions:

eliot (0.8.0)
eliot-tree (15.3.0)

Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 23 2015, 02:52:03)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

```
%> uname -a
Darwin dmt 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 x86_64
```
```
%> eliot-tree
Traceback (most recent call last):
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/bin/eliot-tree", line 9, in <module>
    load_entry_point('eliot-tree==15.3.0', 'console_scripts', 'eliot-tree')()
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2582, in load_entry_point
    return ep.load()
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2265, in load
    return self._load()
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2268, in _load
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/eliottree/__init__.py", line 3, in <module>
    from eliottree.tree import Tree
  File "/Users/vg/Devel/DetailsAuto/new/backend/.venv/lib/python3.4/site-packages/eliottree/tree.py", line 129
    return sorted(nodes, key=lambda (_, n): n.task[u'timestamp'])
                                    ^
SyntaxError: invalid syntax
```

**Comment by jonathanj** [comment]
This is actually a Python 3 issue since they removed the tuple destructuring syntax in function signatures. I renamed the issue to better indicate this.
