### ISSUE TITLE
Failure trying to parse a task tree with missing messages

### ISSUE THREAD

**Issue by mithrandi** [jonathanj/eliottree#43]
This often happens because of log rotation; an operation that straddles midnight will have the start action go into the previous day's log, but the end action into the next day's log.

The traceback looks like this:

```
Traceback (most recent call last):
  File "/appenv/bin/eliot-tree", line 11, in <module>
    sys.exit(main())
  File "/appenv/local/lib/python2.7/site-packages/eliottree/_cli.py", line 108, in main
    display_task_tree(args)
  File "/appenv/local/lib/python2.7/site-packages/eliottree/_cli.py", line 58, in display_task_tree
    human_readable=args.human_readable)
  File "/appenv/local/lib/python2.7/site-packages/eliottree/_cli.py", line 46, in build_task_nodes
    return tree.nodes(tree.merge_tasks(tasks, filter_funcs()))
  File "/appenv/local/lib/python2.7/site-packages/eliottree/tree.py", line 176, in merge_tasks
    pending = _merge(tasks)
  File "/appenv/local/lib/python2.7/site-packages/eliottree/tree.py", line 170, in _merge
    node.add_child(_TaskNode(task))
  File "/appenv/local/lib/python2.7/site-packages/eliottree/tree.py", line 80, in add_child
    _add_child(self, node.task['task_level'])
  File "/appenv/local/lib/python2.7/site-packages/eliottree/tree.py", line 77, in _add_child
    _add_child(children[level], levels)
  File "/appenv/local/lib/python2.7/site-packages/eliottree/tree.py", line 74, in _add_child
    level = levels.pop(0)
IndexError: pop from empty list
```

I didn't construct a minimal reproduction yet, but @jonathanj has access to the data that I used; if someone else wants to look into this, just yell at me, and I'll come up with an example.

**Comment by mithrandi** [comment]
Apparently my original diagnosis of the problem was completely wrong. Here's an example that reproduces this traceback (produced from a real example by removing unimportant fields and censoring the action types slightly):
```
{"action_status": "started", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:soap:service:request", "timestamp": 1468931012.307614, "task_level": [1]}
{"timestamp": 1468931012.310445, "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "task_level": [2, 1], "action_status": "started", "action_type": "fusion:blee:service:request"}
{"task_level": [2, 2, 1], "action_status": "started", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:blee:service:message", "timestamp": 1468931012.389764}
{"action_status": "succeeded", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:blee:service:message", "task_level": [2, 2, 2], "timestamp": 1468931012.937855}
{"action_status": "succeeded", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:blee:service:request", "task_level": [2, 3], "timestamp": 1468931012.939039}
{"action_status": "started", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:soap:service:success", "task_level": [3, 1], "timestamp": 1468931012.940192}
{"action_status": "succeeded", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:blee:service:message", "task_level": [2, 2, 2], "timestamp": 1468931012.937855}
{"action_status": "succeeded", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:blee:service:request", "task_level": [2, 3], "timestamp": 1468931012.939039}
{"action_status": "started", "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "action_type": "fusion:soap:service:success", "task_level": [3, 1], "timestamp": 1468931012.940192}
{"timestamp": 1468931012.941202, "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "task_level": [3, 2], "action_status": "succeeded", "action_type": "fusion:soap:service:success"}
{"timestamp": 1468931012.945127, "task_uuid": "bd04e4a8-6ffc-41b9-8132-3e22dbf96f72", "task_level": [4], "action_status": "succeeded", "action_type": "fusion:soap:service:request"}
```
I think the problem has to do with the duplicate messages at `/2/3` and `/3/1`, which strongly suggest a bug in the original code that is outputting these.
